#!groovy
pipeline {
  agent none
  //agent {
  //  dockerfile {
  //    /*
  //     * This assumes that a "Dockerfile" is in the current workspace
  //     * A new container will be build with the args below and the pipeline will run inside that container.
  //     */
  //    args "-v /tmp:/tmp -p 5000:5000"
  //  }
  //}
  stages {
    stage("Create Backend") {
      agent {
        dockerfile {
          filename "Example6/Dockerfile"
          args "-v /tmp:/tmp -p 5000:5000"
        }
      }
      steps {
        sh 'cat /app/index.py'
        sh 'echo "The answer is 42"'
      }
//    stage("foo") {
//      steps {
//        sh 'cat /app/index.py'
//        sh 'echo "The answer is 42"'
//      }
    }
  }
}
