pipeline {
  dir("Example6") {
    sh "pwd"
  } 
  agent {
    dockerfile {
      /*
       * This assumes that a "Dockerfile" is in the current workspace
       * A new container will be build with the args below and the pipeline will run inside that container.
       */
      args "-v /tmp:/tmp -p 5000:5000"
    }
  }
  stages {
    stage("foo") {
      steps {
        sh 'cat /app/index.py'
        sh 'echo "The answer is 42"'
      }
    }
  }
}
